name: Weekly global Tool Linting and Tests
on:
  schedule:
    # Run at midnight every monday
    - cron: '0 0 * * 1'
  repository_dispatch:
    types: [run-all-tool-tests-command]
jobs:
  setup:
    name: Setup cache and determine changed repositories
    uses: bernt-matthias/tools-iuc/.github/workflows/job_setup.yaml
    with:
      # default-galaxy-fork: galaxyproject
      # default-galaxy-branch: release_22.05
      max-chunks: 40
    secrets:
      PAT: ${{ secrets.PAT }}
  test:
    name: Test tools
    needs: setup
    uses: bernt-matthias/tools-iuc/.github/workflows/job_test.yaml
    with:
      galaxy-fork: ${{ needs.setup.outputs.galaxy-fork }}
      galaxy-branch: ${{ needs.setup.outputs.galaxy-branch }}
      repository-list: ${{ needs.setup.outputs.repository-list }}
      chunk-count: ${{ needs.setup.outputs.chunk-count }}
      chunk-list: ${{ needs.setup.outputs.chunk-list }}
      galaxy-head-sha: ${{ needs.setup.outputs.galaxy-head-sha }}
      test-timeout: 900
    secrets:
      PAT: ${{ secrets.PAT }}
