name: Deploy Tools
on:
  workflow_call:
    inputs:
      galaxy-head-sha:
        description: 'hash of the latest commit in the Galaxy repo'
        required: true
        type: string
      repository-list:
        description: 'list of repositories to deploy'
        required: true
        type: string
      repository-owner:
        description: 'owner, ie main fork, of the repository (deploy will only run for this fork)'
        required: true
        type: string
      python-version-list:
        description: 'Python versions (stringified JSON array)'
        default: "[\"3.7\"]"
        required: false
        type: string
    secrets:
      TTS_API_KEY:
        required: true
      TS_API_KEY:
        required: true

jobs:
  # deploy the tools to the toolsheds (first TTS for testing)
  deploy:
    name: Deploy
    if: ${{ (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' ) && github.repository_owner == inputs.repository-owner }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJson(inputs.python-version-list) }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache .cache/pip
      uses: actions/cache@v2
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: pip_cache_py_${{ matrix.python-version }}_gxy_${{ inputs.galaxy-head-sha }}
    - name: Deploy on testtoolshed
      uses: galaxyproject/planemo-ci-action@v1
      with:
        mode: deploy
        repository-list: ${{ inputs.repository-list }}
        shed-target: testtoolshed
        shed-key: ${{ secrets.TTS_API_KEY }}
      continue-on-error: true
    - name: Deploy on toolshed
      uses: galaxyproject/planemo-ci-action@v1
      with:
        mode: deploy
        repository-list: ${{ inputs.repository-list }}
        shed-target: toolshed
        shed-key: ${{ secrets.TS_API_KEY }}